[package]
name = "corepolicy-manager-wrapper"
version = "0.1.2-beta4"
edition = "2024"
license = "MPL-2.0"
description = "Wrapper crate that packages the CoreShift Policy daemon for CorePolicyManager"

[[bin]]
name = "corepolicy"
path = "src/main.rs"

[dependencies]
coreshift-policy = { git = "https://github.com/CoreShiftD/CoreShift-Policy", tag = "v0.3.2-beta5" }
