[package]
name = "corepolicy-manager-wrapper"
version = "0.8.0"
edition = "2024"
license = "MPL-2.0"
description = "Wrapper crate that packages the CoreShift Policy daemon for CorePolicyManager"

[[bin]]
name = "corepolicy"
path = "src/main.rs"

[dependencies]
coreshift-policy = { git = "https://github.com/CoreShiftD/CoreShift-Policy.git", tag = "v0.8.0" }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
debug = 0
incremental = false
strip = "none"
